### ISSUE TITLE
Merchant Payout design 

### ISSUE THREAD

**Issue by juliexxia** [sendchinatownlove/ruby#50]
Pseudocode flow for merchant payout

```
# new
Model: MerchantPayout
Fields: Seller seller, integer totalAmount, [ ] Item items

# new
Model: Payout
Fields: [ ] MerchantPayout payouts, datetime created
On create -> 
    lastPayoutDatetime = check Payouts table for last payout datetime
    for (items created since lastPayoutDatetime):
        aggregate by seller
    create MerchantPayout objects
    prettyprint MerchantPayout objects somewhere
```

**Comment by jtmckibb** [comment]
I'm not sure if we need a Payout to aggregate all of the MerchantPayouts. I'm not sure if we'll be paying the merchants all at the same time / on a regular cadence that aligns. But maybe we will – but we want to have flexibility.

We should also store some information of how we paid the merchant. Something like PayoutType or TenderType, as an enum: Cash, Check, WeChat Pay (i dunno) — and depending on the PayoutType it would have different associated details. Cash might be date withdrew, date delivered, whose bank account? Check might be check number, date written, date delivered, date cashed? WeChat Pay might be a transaction ID.

Just some things to consider! I'll think through some other things as well.

**Comment by juliexxia** [comment]
> I'm not sure if we need a Payout to aggregate all of the MerchantPayouts. I'm not sure if we'll be paying the merchants all at the same time / on a regular cadence that aligns. But maybe we will – but we want to have flexibility.

Hm that's interesting, so you think we'll want the functionality to trigger individual payouts? That makes sense. Would be nice to have both since I imagine if we get quite a few merchants it'll be tedious to do them all individually.

> We should also store some information of how we paid the merchant. Something like PayoutType or TenderType, as an enum: Cash, Check, WeChat Pay (i dunno) — and depending on the PayoutType it would have different associated details. Cash might be date withdrew, date delivered, whose bank account? Check might be check number, date written, date delivered, date cashed? WeChat Pay might be a transaction ID.

Is all the money not coming out of whatever bank account is linked to receive for square? Also sounds like this is going to need to be an interactive tool then where the user can do more than just press a "give me details for x merchant" button. Maybe nothing more than getPayout(merchant, type(...)) though. 

Another question is do we want to integrate the gift card code print out into these objects/flows as well or should that be done separately. I guess an important question is - are these places open? Will customers be wanting to use the gift cards right away? If they are open, I imagine we'll be wanting to give merchants payouts quickly and regularly so they already have the amounts on the gift cards when the gift cards are used. If not, I guess we just need to get them the funds sometime before they reopen for business. 

Wonder if we can collect merchant emails and autosend gift card emails as part of this. Maybe a v2 feature. It's probably nice to be able to customize them. 

Is the "seller_gift_card_id" field on gift_card_details the gift card code?

**Comment by juliexxia** [comment]
This is also going to have to handle how to cover square fees (if we don't get those waived)

**Comment by jtmckibb** [comment]
Gonna close this while we put it on ice
